package com.studio.planeshift.client.render;

import com.studio.planeshift.common.entity.EnemyRigProfile;
import com.studio.planeshift.PlaneShift;
import java.util.EnumMap;
import java.util.Map;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.util.Mth;

/**
 * Production low-poly geometry for the PlaneShift enemy cast.
 *
 * <p>Every {@link EnemyRigProfile} owns a different baked mesh.  The old shared rig changed only
 * scale and visibility, which meant a plant, beetle and monarch were recognisably the same biped.
 * These layers follow the original turnarounds in {@code tools/art_sources}: leaves are modelled
 * leaves, shells have volume, crawlers have six legs, the torpedo is horizontal, and the boss has
 * a separate jaw, horns, mantle and tail.  The common class only shares animation plumbing.
 *
 * <p>All sheets are 128x128.  Broad material families occupy stable quadrants so the exact UV
 * images can be regenerated by {@code tools/EnemyTextureGen.java} without Blockbench at build
 * time.  Runtime remains dependency-free.
 */
public final class BespokeEnemyModel extends EntityModel<CourseEnemyRenderState> {

    private static final Map<EnemyRigProfile, ModelLayerLocation> LAYERS = new EnumMap<>(EnemyRigProfile.class);

    static {
        for (EnemyRigProfile profile : EnemyRigProfile.values()) {
            if (profile != EnemyRigProfile.TOAD) {
                LAYERS.put(profile, new ModelLayerLocation(
                        PlaneShift.id("enemy/" + profile.name().toLowerCase()), "main"));
            }
        }
    }

    private static final String[] PARTS = {
        "body", "head", "jaw", "snout", "shell", "left_arm", "right_arm",
        "left_leg", "right_leg", "left_wing", "right_wing", "tail", "tail_tip",
        "detail_1", "detail_2", "detail_3", "detail_4", "detail_5", "detail_6",
        "detail_7", "detail_8", "detail_9", "detail_10", "detail_11", "detail_12"
    };

    private final EnemyRigProfile profile;
    private final ModelPart body;
    private final ModelPart head;
    private final ModelPart jaw;
    private final ModelPart snout;
    private final ModelPart shell;
    private final ModelPart leftArm;
    private final ModelPart rightArm;
    private final ModelPart leftLeg;
    private final ModelPart rightLeg;
    private final ModelPart leftWing;
    private final ModelPart rightWing;
    private final ModelPart tail;
    private final ModelPart tailTip;
    private final ModelPart[] details;

    public BespokeEnemyModel(ModelPart root, EnemyRigProfile profile) {
        super(root);
        this.profile = profile;
        body = root.getChild("body");
        head = root.getChild("head");
        jaw = root.getChild("jaw");
        snout = root.getChild("snout");
        shell = root.getChild("shell");
        leftArm = root.getChild("left_arm");
        rightArm = root.getChild("right_arm");
        leftLeg = root.getChild("left_leg");
        rightLeg = root.getChild("right_leg");
        leftWing = root.getChild("left_wing");
        rightWing = root.getChild("right_wing");
        tail = root.getChild("tail");
        tailTip = root.getChild("tail_tip");
        details = new ModelPart[] {
            root.getChild("detail_1"), root.getChild("detail_2"), root.getChild("detail_3"),
            root.getChild("detail_4"), root.getChild("detail_5"), root.getChild("detail_6"),
            root.getChild("detail_7"), root.getChild("detail_8"), root.getChild("detail_9"),
            root.getChild("detail_10"), root.getChild("detail_11"), root.getChild("detail_12")
        };
    }

    public static ModelLayerLocation layer(EnemyRigProfile profile) {
        ModelLayerLocation location = LAYERS.get(profile);
        if (location == null) {
            throw new IllegalArgumentException("No enemy layer for " + profile);
        }
        return location;
    }

    public static LayerDefinition createLayer(EnemyRigProfile profile) {
        return switch (profile) {
            case GOOMBA -> goomba();
            case KOOPA -> koopa();
            case THWOMP -> thwomp();
            case BULLET_BILL -> bulletBill();
            case BOO -> boo();
            case LAKITU -> lakitu();
            case HAMMER_BRO -> hammerBro();
            case SPINY -> spiny();
            case BUZZY_BEETLE -> buzzyBeetle();
            case PIRANHA_PLANT -> piranhaPlant();
            case BOWSER -> bowser();
            case TOAD -> throw new IllegalArgumentException("Villager uses ToadModel");
        };
    }

    private static MeshDefinition emptyMesh() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        for (String name : PARTS) {
            root.addOrReplaceChild(name, CubeListBuilder.create(), PartPose.ZERO);
        }
        return mesh;
    }

    private static LayerDefinition finish(MeshDefinition mesh) {
        return LayerDefinition.create(mesh, 128, 128);
    }

    private static CubeListBuilder box(int u, int v, float x, float y, float z,
                                       float width, float height, float depth) {
        return CubeListBuilder.create().texOffs(u, v).addBox(x, y, z, width, height, depth);
    }

    private static PartPose pose(float x, float y, float z) {
        return PartPose.offset(x, y, z);
    }

    private static PartPose pose(float x, float y, float z, float xr, float yr, float zr) {
        return PartPose.offsetAndRotation(x, y, z, xr, yr, zr);
    }

    /**
     * The face contract.
     *
     * <p>Every rig below obeys one rule that is invisible in code and catastrophic to break, so it
     * is written down here rather than rediscovered.
     *
     * <p>{@code EnemyTextureGen} paints these 128x128 sheets as six flat material regions, at
     * origins (0,0), (64,0), (0,40), (64,40), (0,80) and (64,80). A box does not pick a picture, it
     * picks a <em>material</em> — which is why every {@code texOffs} in this file is one of those
     * six and never anything in between. A UV of, say, (32,48) starts partway through one region
     * and runs into the next, so the box samples two materials with a seam through the middle. An
     * earlier rewrite of this whole file did exactly that, using vanilla player-model coordinates
     * from a 64x64 skin, and every enemy in the mod sampled the wrong part of its own texture.
     *
     * <p>The second half of the rule is tighter. Two regions are not flat: the generator paints a
     * <em>face</em> into them, sized for one specific box. {@code sideFace(g, u, v, w, h, depth)}
     * wraps eyes around a box of exactly those dimensions, so the part carrying the face has to be
     * that size or the eyes land on its ear. Per profile:
     *
     * <pre>
     *   SPROUTLING  body 12x9x8   @(0,0)    head plate 10x6 @(0,80)
     *   GECKO       head  8x6x7   @(64,0)   muzzle      6x3 @(0,80)
     *   CRUSHER     body 16x14x8  @(0,0)    head plate 10x7 @(0,80)
     *   FLYER       head 10x10x5  @(64,0)
     *   WISP        body 12x10x10 @(0,0)    head plate  8x5 @(0,80)
     *   RIDER       head  7x6x6   @(64,0)   muzzle      5x3 @(0,80)
     *   WARRIOR     head  8x6x7   @(64,0)   muzzle      6x3 @(0,80)
     *   CRAWLER     body 14x7x10  @(0,0)    head plate  8x4 @(0,80)
     *   BEETLE      head 10x7x7   @(64,0)
     *   PLANT       maw  12x7x10  @(64,0)   mouth plate 10x8 @(0,80)
     *   BOSS        head 12x8x10  @(64,0)   muzzle     10x5 @(0,80)
     * </pre>
     *
     * <p>Everything else is free. Detail parts can be any size at any of the six origins, which is
     * what makes it cheap to add the horns, brows, teeth and studs that turn a coloured box into a
     * recognisable creature.
     */
    private static LayerDefinition goomba() {
        MeshDefinition mesh = emptyMesh();
        PartDefinition r = mesh.getRoot();
        // Head-body, one mass. A Goomba is almost entirely face, so the face box IS the creature
        // and the legs are an afterthought hanging off the bottom.
        r.addOrReplaceChild("body", box(0, 0, -6, -9, -4, 12, 9, 8), pose(0, 21, 0));
        r.addOrReplaceChild("head", box(0, 80, -5, -3, -0.5F, 10, 6, 1), pose(0, 16, -4.2F));
        // Brow ridge, jutting forward over the eyes. This one part does most of the work of making
        // it read as cross rather than blank.
        r.addOrReplaceChild("snout", box(64, 80, -6, -1.5F, -1, 12, 3, 2), pose(0, 13.5F, -4));
        r.addOrReplaceChild("left_leg", box(0, 40, -3.5F, 0, -3, 7, 3, 6), pose(3.5F, 21, 0));
        r.addOrReplaceChild("right_leg", box(0, 40, -3.5F, 0, -3, 7, 3, 6), pose(-3.5F, 21, 0));
        // Angled brows over each eye.
        r.addOrReplaceChild("detail_1", box(64, 80, -3, -1, -0.5F, 5, 2, 1), pose(-2.6F, 14.4F, -4.6F, 0, 0, 0.32F));
        r.addOrReplaceChild("detail_2", box(64, 80, -2, -1, -0.5F, 5, 2, 1), pose(2.6F, 14.4F, -4.6F, 0, 0, -0.32F));
        // Two fangs at the lower lip.
        r.addOrReplaceChild("detail_3", box(64, 40, -1, 0, -0.5F, 2, 2, 1), pose(-2, 18.6F, -4.4F));
        r.addOrReplaceChild("detail_4", box(64, 40, -1, 0, -0.5F, 2, 2, 1), pose(2, 18.6F, -4.4F));
        // A short stalk on the crown, so the silhouette is not a plain dome from behind.
        r.addOrReplaceChild("detail_5", box(64, 40, -1.5F, -3, -1.5F, 3, 3, 3), pose(0, 12, 0));
        r.addOrReplaceChild("detail_6", box(64, 40, -2.5F, -1, -1, 5, 2, 2), pose(0, 10.5F, 0));
        return finish(mesh);
    }

    private static LayerDefinition koopa() {
        MeshDefinition mesh = emptyMesh();
        PartDefinition r = mesh.getRoot();
        r.addOrReplaceChild("body", box(0, 0, -4, -9, -3, 8, 9, 6), pose(0, 19, 0));
        // The shell is the read. Wide, domed, sitting proud of the back rather than flush with it.
        r.addOrReplaceChild("shell", box(64, 40, -5.5F, -7, -1, 11, 11, 5), pose(0, 17, 2.5F));
        r.addOrReplaceChild("head", box(64, 0, -4, -6, -3.5F, 8, 6, 7), pose(0, 11, -1));
        r.addOrReplaceChild("snout", box(0, 80, -3, -1.5F, -3, 6, 3, 3), pose(0, 9.5F, -4));
        r.addOrReplaceChild("jaw", box(0, 80, -2.5F, 0, -2.5F, 5, 2, 3), pose(0, 11, -4, 0.12F, 0, 0));
        r.addOrReplaceChild("left_arm", box(0, 40, 0, -1, -1.5F, 3, 7, 3), pose(4, 12, 0, 0, 0, -0.14F));
        r.addOrReplaceChild("right_arm", box(0, 40, -3, -1, -1.5F, 3, 7, 3), pose(-4, 12, 0, 0, 0, 0.14F));
        r.addOrReplaceChild("left_leg", box(0, 40, -1.5F, 0, -2, 3, 5, 5), pose(2.5F, 19, 0));
        r.addOrReplaceChild("right_leg", box(0, 40, -1.5F, 0, -2, 3, 5, 5), pose(-2.5F, 19, 0));
        r.addOrReplaceChild("tail", box(64, 40, -2, -2, 0, 4, 4, 5), pose(0, 20, 4, 0.4F, 0, 0));
        // Shell rim, a lighter band around the dome.
        r.addOrReplaceChild("detail_1", box(64, 80, -6, -1, -0.5F, 12, 2, 5), pose(0, 17.5F, 2.5F));
        // Two scutes on the shell so it is not a smooth blob in profile.
        r.addOrReplaceChild("detail_2", box(64, 80, -2, -2, -0.5F, 4, 4, 1), pose(0, 13.5F, 7.6F));
        // Eyes, standing off the head.
        r.addOrReplaceChild("detail_3", box(64, 80, -1.5F, -1.5F, -1, 3, 3, 2), pose(-2.4F, 8, -3.6F));
        r.addOrReplaceChild("detail_4", box(64, 80, -1.5F, -1.5F, -1, 3, 3, 2), pose(2.4F, 8, -3.6F));
        return finish(mesh);
    }

    private static LayerDefinition thwomp() {
        MeshDefinition mesh = emptyMesh();
        PartDefinition r = mesh.getRoot();
        // One heavy slab, exactly the size the face is painted for.
        r.addOrReplaceChild("body", box(0, 0, -8, -14, -4, 16, 14, 8), pose(0, 21, 0));
        r.addOrReplaceChild("head", box(0, 80, -5, -4, -0.5F, 10, 7, 1), pose(0, 12, -4.2F));
        // Heavy brow: the single part that makes a stone block look furious.
        r.addOrReplaceChild("snout", box(64, 80, -7, -2, -1, 14, 3, 2), pose(0, 9, -3.6F));
        // Corner studs. A Thwomp is masonry, and masonry has edges.
        float[][] studs = {{-6.5F, 9.5F}, {6.5F, 9.5F}, {-6.5F, 19.5F}, {6.5F, 19.5F}};
        for (int i = 0; i < studs.length; i++) {
            r.addOrReplaceChild("detail_" + (i + 1), box(64, 40, -1.5F, -1.5F, -1.5F, 3, 3, 3),
                    pose(studs[i][0], studs[i][1], 0));
        }
        // Gritted teeth along the lower edge of the face.
        r.addOrReplaceChild("detail_5", box(64, 40, -4, 0, -0.5F, 8, 2, 1), pose(0, 16, -4.4F));
        // A capstone and a base course, so the slab has a top and a bottom.
        r.addOrReplaceChild("detail_6", box(64, 40, -8.5F, -2, -4.5F, 17, 2, 9), pose(0, 8.5F, 0));
        r.addOrReplaceChild("detail_7", box(64, 40, -8.5F, -2, -4.5F, 17, 2, 9), pose(0, 22, 0));
        r.addOrReplaceChild("detail_8", box(64, 80, -2, -1, -0.5F, 4, 2, 1), pose(0, 10.5F, -4.4F));
        return finish(mesh);
    }

    private static LayerDefinition bulletBill() {
        MeshDefinition mesh = emptyMesh();
        PartDefinition r = mesh.getRoot();
        // Barrel: long, smooth, unbroken. This is the whole read, and the previous rig buried it
        // under two ten-long wings and a tail fin, which made an insect rather than a shell.
        r.addOrReplaceChild("body", box(0, 0, -5, -5, -7, 10, 10, 16), pose(0, 15, 0));
        // Nose cap: exactly 10x10x5, because that is the box the face is painted around.
        r.addOrReplaceChild("head", box(64, 0, -5, -5, -4, 10, 10, 5), pose(0, 15, -8));
        r.addOrReplaceChild("tail", box(64, 40, -4, -4, 0, 8, 8, 3), pose(0, 15, 9));
        r.addOrReplaceChild("left_arm", box(0, 40, 0, -1, -2, 5, 2, 6), pose(5, 15, 1, 0, 0, -0.2F));
        r.addOrReplaceChild("right_arm", box(0, 40, -5, -1, -2, 5, 2, 6), pose(-5, 15, 1, 0, 0, 0.2F));
        // Vestigial wings, kept because the FLYER animation flaps them and a little motion at the
        // fin sells "under power" better than a rigid bar.
        r.addOrReplaceChild("left_wing", box(0, 40, 0, -0.5F, -1.5F, 4, 1, 4), pose(5, 12, 3, 0, 0, -0.42F));
        r.addOrReplaceChild("right_wing", box(0, 40, -4, -0.5F, -1.5F, 4, 1, 4), pose(-5, 12, 3, 0, 0, 0.42F));
        // Nose ring and rivets, so the cap reads as a separate cast piece.
        r.addOrReplaceChild("detail_1", box(64, 40, -5.5F, -5.5F, -0.5F, 11, 11, 1), pose(0, 15, -3.4F));
        r.addOrReplaceChild("detail_2", box(64, 80, -1, -1, -0.5F, 2, 2, 1), pose(-4, 15, -12.2F));
        r.addOrReplaceChild("detail_3", box(64, 80, -1, -1, -0.5F, 2, 2, 1), pose(4, 15, -12.2F));
        // Exhaust flare at the back.
        r.addOrReplaceChild("detail_4", box(64, 40, -2.5F, -2.5F, 0, 5, 5, 2), pose(0, 15, 12));
        return finish(mesh);
    }

    private static LayerDefinition boo() {
        MeshDefinition mesh = emptyMesh();
        PartDefinition r = mesh.getRoot();
        // 12x10x10 exactly: this is the box the WISP face is painted around.
        r.addOrReplaceChild("body", box(0, 0, -6, -6, -5, 12, 10, 10), pose(0, 13, 0));
        // Face plate at (0,80), 8x5 — the flat face the generator paints there, not the side face.
        r.addOrReplaceChild("head", box(0, 80, -4, -2.5F, -0.5F, 8, 5, 1), pose(0, 12, -5.4F));
        // Shoulders, narrower and set back. The two-stage taper is what rounds the silhouette and
        // stops it reading as a floating plate.
        r.addOrReplaceChild("shell", box(0, 40, -5, -2, -4, 10, 5, 8), pose(0, 18, 0.5F));
        // Arms on the body material, not the trim region — trim is the pink reserved for the
        // tongue, and a ghost with pink hands is not the look.
        r.addOrReplaceChild("left_arm", box(0, 40, -1.5F, -1.5F, -1.5F, 3, 3, 3),
                pose(6.5F, 14, -2.5F, 0, -0.5F, 0));
        r.addOrReplaceChild("right_arm", box(0, 40, -1.5F, -1.5F, -1.5F, 3, 3, 3),
                pose(-6.5F, 14, -2.5F, 0, 0.5F, 0));
        // Ragged hem, tallest in the middle. A ghost has no flat bottom.
        for (int i = 0; i < 5; i++) {
            float x = -4.0F + i * 2.0F;
            int height = 5 - Math.abs(i - 2);
            r.addOrReplaceChild("detail_" + (i + 1), box(64, 40, -1, 0, -1, 2, height, 2),
                    pose(x, 21, 0, 0, 0, (i - 2) * 0.09F));
        }
        // Tongue, just below the face. Cheap, and it is half of what makes a Boo a Boo.
        r.addOrReplaceChild("detail_6", box(64, 80, -1.5F, 0, -0.5F, 3, 2, 1), pose(0, 15.5F, -5.6F));
        return finish(mesh);
    }

    private static LayerDefinition lakitu() {
        MeshDefinition mesh = emptyMesh();
        PartDefinition r = mesh.getRoot();
        // The cloud is the character's ground. Built from a slab plus four puffs so its outline is
        // lumpy rather than rectangular.
        r.addOrReplaceChild("shell", box(0, 0, -8, -3, -6, 16, 5, 12), pose(0, 20, 0));
        float[][] puffs = {{-7, 19, -4}, {7, 19, -4}, {-6, 19, 5}, {6, 19, 5}};
        for (int i = 0; i < puffs.length; i++) {
            r.addOrReplaceChild("detail_" + (i + 1), box(0, 0, -3, -3, -3, 6, 6, 6),
                    pose(puffs[i][0], puffs[i][1], puffs[i][2]));
        }
        r.addOrReplaceChild("body", box(0, 40, -3.5F, -6, -2.5F, 7, 6, 5), pose(0, 18, 0));
        r.addOrReplaceChild("head", box(64, 0, -3.5F, -6, -3, 7, 6, 6), pose(0, 12, 0));
        r.addOrReplaceChild("snout", box(0, 80, -2.5F, -1.5F, -1.5F, 5, 3, 3), pose(0, 10, -3.5F));
        r.addOrReplaceChild("left_arm", box(0, 40, 0, 0, -1, 2, 5, 2), pose(3.5F, 13, 0, -0.65F, 0, -0.25F));
        r.addOrReplaceChild("right_arm", box(0, 40, -2, 0, -1, 2, 5, 2), pose(-3.5F, 13, 0, -0.65F, 0, 0.25F));
        // Goggles across the eyes, and a shell on the back.
        r.addOrReplaceChild("detail_5", box(64, 80, -3.5F, -1.5F, -0.5F, 7, 3, 1), pose(0, 8.5F, -3.2F));
        r.addOrReplaceChild("detail_6", box(64, 40, -3.5F, -4, -1, 7, 6, 3), pose(0, 17, 2.5F));
        return finish(mesh);
    }

    private static LayerDefinition hammerBro() {
        MeshDefinition mesh = emptyMesh();
        PartDefinition r = mesh.getRoot();
        r.addOrReplaceChild("body", box(0, 0, -4.5F, -10, -3, 9, 10, 6), pose(0, 19, 0));
        r.addOrReplaceChild("shell", box(64, 40, -5.5F, -8, -1, 11, 11, 5), pose(0, 17, 2.5F));
        r.addOrReplaceChild("head", box(64, 0, -4, -6, -3.5F, 8, 6, 7), pose(0, 10, 0));
        r.addOrReplaceChild("snout", box(0, 80, -3, -1.5F, -3, 6, 3, 3), pose(0, 8.5F, -3.5F));
        r.addOrReplaceChild("left_arm", box(0, 40, 0, -1, -2, 4, 8, 4), pose(5, 11, 0, 0, 0, -0.2F));
        r.addOrReplaceChild("right_arm", box(0, 40, -4, -1, -2, 4, 8, 4), pose(-5, 11, 0, 0, 0, 0.2F));
        r.addOrReplaceChild("left_leg", box(0, 40, -2, 0, -2.5F, 4, 5, 5), pose(3, 19, 0));
        r.addOrReplaceChild("right_leg", box(0, 40, -2, 0, -2.5F, 4, 5, 5), pose(-3, 19, 0));
        // The helmet is the whole reason a Hammer Bro is not a Koopa: a hard brim across the brow.
        r.addOrReplaceChild("detail_1", box(64, 40, -4.5F, -2, -4, 9, 3, 8), pose(0, 5.5F, 0));
        r.addOrReplaceChild("detail_2", box(64, 40, -5, -1, -1.5F, 10, 2, 3), pose(0, 5.5F, -3.5F));
        r.addOrReplaceChild("detail_3", box(64, 80, -6, -1, -0.5F, 12, 2, 5), pose(0, 17.5F, 2.5F));
        r.addOrReplaceChild("detail_4", box(64, 80, -1.5F, -1.5F, -1, 3, 3, 2), pose(-2.4F, 7.5F, -3.6F));
        r.addOrReplaceChild("detail_5", box(64, 80, -1.5F, -1.5F, -1, 3, 3, 2), pose(2.4F, 7.5F, -3.6F));
        return finish(mesh);
    }

    private static LayerDefinition spiny() {
        MeshDefinition mesh = emptyMesh();
        PartDefinition r = mesh.getRoot();
        // 14x7x10: the box the CRAB face is painted around.
        r.addOrReplaceChild("body", box(0, 0, -7, -5, -5, 14, 7, 10), pose(0, 18, 0));
        r.addOrReplaceChild("head", box(0, 80, -4, -2, -0.5F, 8, 4, 1), pose(0, 17, -5.2F));
        // Domed shell over the back — the thing the spikes stand on, and the thing that tells the
        // player not to jump here.
        r.addOrReplaceChild("shell", box(64, 40, -6.5F, -4, -4.5F, 13, 4, 9), pose(0, 13.5F, 0));
        r.addOrReplaceChild("left_leg", box(0, 40, 0, 0, -2, 4, 3, 4), pose(5, 21, -2, 0, 0, -0.15F));
        r.addOrReplaceChild("right_leg", box(0, 40, -4, 0, -2, 4, 3, 4), pose(-5, 21, -2, 0, 0, 0.15F));
        // Six spikes, alternating height so the back is jagged rather than a crown of matched pins.
        float[][] spikes = {{-4.5F, -3}, {0, -4}, {4.5F, -3}, {-4.5F, 3}, {0, 4}, {4.5F, 3}};
        for (int i = 0; i < spikes.length; i++) {
            float h = (i % 3 == 1) ? 5 : 4;
            r.addOrReplaceChild("detail_" + (i + 1), box(64, 80, -1.5F, -h, -1.5F, 3, h, 3),
                    pose(spikes[i][0], 13.5F, spikes[i][1]));
        }
        // Eyes, set wide and low.
        r.addOrReplaceChild("detail_7", box(64, 80, -1.5F, -1.5F, -1, 3, 3, 2), pose(-3, 16, -4.8F));
        r.addOrReplaceChild("detail_8", box(64, 80, -1.5F, -1.5F, -1, 3, 3, 2), pose(3, 16, -4.8F));
        // Front feet. It walks on four, and two made it look like it was dragging itself.
        r.addOrReplaceChild("left_arm", box(0, 40, 0, 0, -2, 4, 3, 4), pose(5, 21, 3, 0, 0, -0.15F));
        r.addOrReplaceChild("right_arm", box(0, 40, -4, 0, -2, 4, 3, 4), pose(-5, 21, 3, 0, 0, 0.15F));
        return finish(mesh);
    }

    private static LayerDefinition buzzyBeetle() {
        MeshDefinition mesh = emptyMesh();
        PartDefinition r = mesh.getRoot();
        r.addOrReplaceChild("body", box(0, 0, -5, -4, -5, 10, 4, 10), pose(0, 20, 0));
        // Wide, low, glossy carapace: a Buzzy Beetle is a helmet with feet.
        r.addOrReplaceChild("shell", box(64, 40, -7, -6, -6, 14, 6, 12), pose(0, 20, 0));
        r.addOrReplaceChild("head", box(64, 0, -5, -7, -3.5F, 10, 7, 7), pose(0, 20, -5));
        r.addOrReplaceChild("left_arm", box(0, 40, 0, 0, -1.5F, 3, 3, 3), pose(5.5F, 21, -3));
        r.addOrReplaceChild("right_arm", box(0, 40, -3, 0, -1.5F, 3, 3, 3), pose(-5.5F, 21, -3));
        r.addOrReplaceChild("left_leg", box(0, 40, 0, 0, -1.5F, 3, 3, 3), pose(5.5F, 21, 3));
        r.addOrReplaceChild("right_leg", box(0, 40, -3, 0, -1.5F, 3, 3, 3), pose(-5.5F, 21, 3));
        // Rim around the carapace, and a ridge down the middle.
        r.addOrReplaceChild("detail_1", box(64, 80, -7.5F, -1, -6.5F, 15, 2, 13), pose(0, 20.5F, 0));
        r.addOrReplaceChild("detail_2", box(64, 80, -1.5F, -2, -6, 3, 2, 12), pose(0, 14.5F, 0));
        r.addOrReplaceChild("detail_3", box(64, 80, -1.5F, -1.5F, -1, 3, 3, 2), pose(-2.6F, 16.5F, -8.2F));
        r.addOrReplaceChild("detail_4", box(64, 80, -1.5F, -1.5F, -1, 3, 3, 2), pose(2.6F, 16.5F, -8.2F));
        // Antennae, and a tail nub so the shell is not symmetrical front to back.
        r.addOrReplaceChild("detail_5", box(64, 40, -0.5F, -3, -0.5F, 1, 3, 1), pose(-2.5F, 14, -6, -0.3F, 0, -0.25F));
        r.addOrReplaceChild("detail_6", box(64, 40, -0.5F, -3, -0.5F, 1, 3, 1), pose(2.5F, 14, -6, -0.3F, 0, 0.25F));
        r.addOrReplaceChild("tail", box(64, 40, -2, -1.5F, 0, 4, 3, 3), pose(0, 21, 6));
        return finish(mesh);
    }

    private static LayerDefinition piranhaPlant() {
        MeshDefinition mesh = emptyMesh();
        PartDefinition r = mesh.getRoot();
        // 12x7x10: the box the PLANT mouth is painted around. Split into an upper and a lower half
        // so the jaw can open, which is the only animation this creature needs.
        r.addOrReplaceChild("head", box(64, 0, -6, -7, -5, 12, 7, 10), pose(0, 12, 0));
        r.addOrReplaceChild("jaw", box(64, 0, -6, 0, -5, 12, 7, 10), pose(0, 12, 0, 0.22F, 0, 0));
        r.addOrReplaceChild("body", box(0, 80, -5, -4, -0.5F, 10, 8, 1), pose(0, 12, -5.2F));
        // Stem in two tapering segments, so it bends instead of being a pipe.
        r.addOrReplaceChild("tail", box(0, 40, -2.5F, 0, -2.5F, 5, 7, 5), pose(0, 13, 1));
        r.addOrReplaceChild("tail_tip", box(0, 40, -2, 0, -2, 4, 6, 4), pose(0, 19, 1));
        // Teeth: four upper, four lower, so the maw has a bite rather than an outline.
        for (int i = 0; i < 4; i++) {
            float x = -4.5F + i * 3;
            r.addOrReplaceChild("detail_" + (i + 1), box(64, 40, -1, 0, -0.5F, 2, 2, 1),
                    pose(x, 5.6F, -5.2F));
            r.addOrReplaceChild("detail_" + (i + 5), box(64, 40, -1, -2, -0.5F, 2, 2, 1),
                    pose(x, 12, -5.2F, 0.22F, 0, 0));
        }
        // Two leaves at the base.
        r.addOrReplaceChild("detail_9", box(0, 40, 0, -1, -2, 6, 2, 4), pose(2.5F, 20, 1, 0, 0.4F, -0.3F));
        r.addOrReplaceChild("detail_10", box(0, 40, -6, -1, -2, 6, 2, 4), pose(-2.5F, 20, 1, 0, -0.4F, 0.3F));
        return finish(mesh);
    }

    private static LayerDefinition bowser() {
        MeshDefinition mesh = emptyMesh();
        PartDefinition r = mesh.getRoot();
        r.addOrReplaceChild("body", box(0, 0, -8, -13, -5, 16, 13, 10), pose(0, 20, 0));
        r.addOrReplaceChild("shell", box(64, 40, -9, -12, -2, 18, 14, 6), pose(0, 17, 4));
        // 12x8x10: the box the BOSS face is painted around.
        r.addOrReplaceChild("head", box(64, 0, -6, -8, -6, 12, 8, 10), pose(0, 7, -1));
        r.addOrReplaceChild("snout", box(0, 80, -5, -3, -6, 10, 5, 6), pose(0, 4, -6));
        r.addOrReplaceChild("jaw", box(0, 80, -5, -1, -6, 10, 4, 6), pose(0, 7, -6, 0.1F, 0, 0));
        r.addOrReplaceChild("left_arm", box(0, 40, 0, -3, -3, 6, 13, 6), pose(8, 9, 0, -0.12F, 0, -0.22F));
        r.addOrReplaceChild("right_arm", box(0, 40, -6, -3, -3, 6, 13, 6), pose(-8, 9, 0, -0.12F, 0, 0.22F));
        r.addOrReplaceChild("left_leg", box(0, 40, -3, -2, -4, 6, 8, 8), pose(6, 18, 0));
        r.addOrReplaceChild("right_leg", box(0, 40, -3, -2, -4, 6, 8, 8), pose(-6, 18, 0));
        r.addOrReplaceChild("tail", box(64, 40, -4, -4, 0, 8, 8, 12), pose(0, 17, 5, 0.35F, 0, 0));
        r.addOrReplaceChild("tail_tip", box(64, 40, -3, -3, 0, 6, 6, 11), pose(0, 20, 15, 0.5F, 0, 0));
        // Horns, swept back and out.
        r.addOrReplaceChild("detail_1", box(64, 80, -1.5F, -7, -1.5F, 3, 7, 3), pose(-4, 0, -2, -0.2F, 0, -0.35F));
        r.addOrReplaceChild("detail_2", box(64, 80, -1.5F, -7, -1.5F, 3, 7, 3), pose(4, 0, -2, -0.2F, 0, 0.35F));
        // Shell spikes, three down the back.
        r.addOrReplaceChild("detail_3", box(64, 80, -2, -5, -2, 4, 5, 4), pose(0, 6, 8, -0.4F, 0, 0));
        r.addOrReplaceChild("detail_4", box(64, 80, -2, -5, -2, 4, 5, 4), pose(-5, 10, 9, -0.2F, 0, -0.3F));
        r.addOrReplaceChild("detail_5", box(64, 80, -2, -5, -2, 4, 5, 4), pose(5, 10, 9, -0.2F, 0, 0.3F));
        // Brow ridge, and two cuffs on the wrists.
        r.addOrReplaceChild("detail_6", box(64, 80, -6.5F, -1.5F, -1, 13, 3, 2), pose(0, 2, -6));
        r.addOrReplaceChild("detail_7", box(64, 40, -3.5F, -1.5F, -3.5F, 7, 3, 7), pose(8, 20, 0));
        r.addOrReplaceChild("detail_8", box(64, 40, -3.5F, -1.5F, -3.5F, 7, 3, 7), pose(-8, 20, 0));
        return finish(mesh);
    }

    @Override
    public void setupAnim(CourseEnemyRenderState state) {
        super.setupAnim(state);
        float speed = Math.min(1.0F, state.walkAnimationSpeed);
        float phase = state.walkAnimationPos * 0.72F;
        float step = Mth.cos(phase) * 0.9F * speed;
        float opposite = Mth.cos(phase + Mth.PI) * 0.9F * speed;
        float idle = Mth.sin(state.ageInTicks * 0.11F);

        head.yRot = state.yRot * Mth.DEG_TO_RAD * 0.55F;
        head.xRot += state.xRot * Mth.DEG_TO_RAD * 0.35F;

        switch (profile) {
            case GOOMBA -> {
                leftLeg.xRot = opposite;
                rightLeg.xRot = step;
                body.y += Math.abs(Mth.sin(phase)) * speed * -0.8F + idle * 0.12F;
                details[0].zRot += idle * 0.08F;
                details[1].zRot += idle * 0.06F;
                details[2].zRot -= idle * 0.06F;
            }
            case KOOPA -> {
                walk(step, opposite, 0.75F);
                tail.yRot = Mth.sin(state.ageInTicks * 0.13F) * 0.22F - step * 0.12F;
                tailTip.yRot = tail.yRot * 1.35F;
            }
            case THWOMP -> {
                body.y += idle * 0.3F;
                float slam = Math.max(0, Mth.sin(state.ageInTicks * 0.12F) - 0.68F) * 2.7F;
                leftArm.y += slam * 4.2F;
                rightArm.y += slam * 4.2F;
                leftLeg.y += slam * 2.5F;
                rightLeg.y += slam * 2.5F;
            }
            case BULLET_BILL -> {
                body.y += idle * 0.3F;
                float flap = Mth.sin(state.ageInTicks * 0.9F) * 0.48F;
                leftWing.zRot += flap;
                rightWing.zRot -= flap;
                leftArm.zRot -= flap * 0.65F;
                rightArm.zRot += flap * 0.65F;
                tail.yRot = Mth.sin(state.ageInTicks * 0.18F) * 0.08F;
            }
            case BOO -> {
                body.y += idle * 0.8F;
                head.y += idle * 0.8F;
                leftArm.y += -idle * 0.35F;
                rightArm.y += idle * 0.35F;
                for (int i = 0; i < details.length; i++) {
                    details[i].xRot = Mth.sin(state.ageInTicks * 0.16F + i * 0.7F) * 0.12F;
                }
            }
            case LAKITU -> {
                float flap = Mth.sin(state.ageInTicks * 0.32F) * 0.22F;
                leftWing.zRot += flap;
                rightWing.zRot -= flap;
                leftArm.xRot += -flap * 0.7F;
                rightArm.xRot += flap * 0.7F;
                details[1].yRot = Mth.sin(state.ageInTicks * 0.18F) * 0.18F;
            }
            case HAMMER_BRO -> {
                walk(step, opposite, 0.82F);
                tail.yRot = -step * 0.12F;
                tailTip.yRot = -step * 0.18F;
                leftArm.zRot -= 0.08F;
                rightArm.zRot += 0.08F;
            }
            case SPINY, BUZZY_BEETLE -> {
                for (int i = 0; i < details.length; i++) {
                    float cycle = Mth.sin(phase * 1.35F + (i % 3) * 0.85F + (i >= 3 ? Mth.PI : 0));
                    details[i].yRot += cycle * 0.25F * speed;
                }
                leftArm.yRot += step * 0.16F;
                rightArm.yRot -= step * 0.16F;
                body.y += Math.abs(Mth.sin(phase * 1.35F)) * speed * -0.18F;
            }
            case PIRANHA_PLANT -> {
                body.zRot = idle * 0.06F;
                head.zRot = Mth.sin(state.ageInTicks * 0.11F + 0.6F) * 0.09F;
                jaw.xRot += 0.12F + (Mth.sin(state.ageInTicks * 0.17F) + 1) * 0.08F;
                leftArm.zRot += idle * 0.12F;
                rightArm.zRot -= idle * 0.12F;
            }
            case BOWSER -> {
                walk(step, opposite, 0.42F);
                body.y += Math.abs(Mth.sin(phase)) * speed * -0.22F;
                tail.yRot = Mth.sin(state.ageInTicks * 0.08F) * 0.16F;
                tailTip.yRot = Mth.sin(state.ageInTicks * 0.08F + 0.5F) * 0.22F;
                jaw.xRot += (Mth.sin(state.ageInTicks * 0.075F) + 1) * 0.035F;
                shell.xRot = idle * 0.012F;
            }
            case TOAD -> {
                // Dedicated ToadModel handles the non-hostile shopkeeper.
            }
        }
    }

    private void walk(float step, float opposite, float armScale) {
        rightLeg.xRot = step;
        leftLeg.xRot = opposite;
        rightArm.xRot = -step * armScale;
        leftArm.xRot = -opposite * armScale;
    }
}
