package com.studio.planeshift.client.render;

import com.studio.planeshift.common.entity.EnemyRigProfile;
import com.studio.planeshift.PlaneShift;
import java.util.EnumMap;
import java.util.Map;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.util.Mth;

/**
 * Production low-poly geometry for the PlaneShift enemy cast.
 *
 * <p>Every {@link EnemyRigProfile} owns a different baked mesh.  The old shared rig changed only
 * scale and visibility, which meant a plant, beetle and monarch were recognisably the same biped.
 * These layers follow the original turnarounds in {@code tools/art_sources}: leaves are modelled
 * leaves, shells have volume, crawlers have six legs, the torpedo is horizontal, and the boss has
 * a separate jaw, horns, mantle and tail.  The common class only shares animation plumbing.
 *
 * <p>All sheets are 128x128.  Broad material families occupy stable quadrants so the exact UV
 * images can be regenerated by {@code tools/EnemyTextureGen.java} without Blockbench at build
 * time.  Runtime remains dependency-free.
 */
public final class BespokeEnemyModel extends EntityModel<CourseEnemyRenderState> {

    private static final Map<EnemyRigProfile, ModelLayerLocation> LAYERS = new EnumMap<>(EnemyRigProfile.class);

    static {
        for (EnemyRigProfile profile : EnemyRigProfile.values()) {
            if (profile != EnemyRigProfile.VILLAGER) {
                LAYERS.put(profile, new ModelLayerLocation(
                        PlaneShift.id("enemy/" + profile.name().toLowerCase()), "main"));
            }
        }
    }

    private static final String[] PARTS = {
        "body", "head", "jaw", "snout", "shell", "left_arm", "right_arm",
        "left_leg", "right_leg", "left_wing", "right_wing", "tail", "tail_tip",
        "detail_1", "detail_2", "detail_3", "detail_4", "detail_5", "detail_6"
    };

    private final EnemyRigProfile profile;
    private final ModelPart body;
    private final ModelPart head;
    private final ModelPart jaw;
    private final ModelPart snout;
    private final ModelPart shell;
    private final ModelPart leftArm;
    private final ModelPart rightArm;
    private final ModelPart leftLeg;
    private final ModelPart rightLeg;
    private final ModelPart leftWing;
    private final ModelPart rightWing;
    private final ModelPart tail;
    private final ModelPart tailTip;
    private final ModelPart[] details;

    public BespokeEnemyModel(ModelPart root, EnemyRigProfile profile) {
        super(root);
        this.profile = profile;
        body = root.getChild("body");
        head = root.getChild("head");
        jaw = root.getChild("jaw");
        snout = root.getChild("snout");
        shell = root.getChild("shell");
        leftArm = root.getChild("left_arm");
        rightArm = root.getChild("right_arm");
        leftLeg = root.getChild("left_leg");
        rightLeg = root.getChild("right_leg");
        leftWing = root.getChild("left_wing");
        rightWing = root.getChild("right_wing");
        tail = root.getChild("tail");
        tailTip = root.getChild("tail_tip");
        details = new ModelPart[] {
            root.getChild("detail_1"), root.getChild("detail_2"), root.getChild("detail_3"),
            root.getChild("detail_4"), root.getChild("detail_5"), root.getChild("detail_6")
        };
    }

    public static ModelLayerLocation layer(EnemyRigProfile profile) {
        ModelLayerLocation location = LAYERS.get(profile);
        if (location == null) {
            throw new IllegalArgumentException("No enemy layer for " + profile);
        }
        return location;
    }

    public static LayerDefinition createLayer(EnemyRigProfile profile) {
        return switch (profile) {
            case SPROUTLING -> sproutling();
            case GECKO -> gecko();
            case CRUSHER -> crusher();
            case FLYER -> torpedoMoth();
            case WISP -> moonWisp();
            case RIDER -> mantaRider();
            case WARRIOR -> pangolin();
            case CRAWLER -> pincushionCrab();
            case BEETLE -> burrowingBeetle();
            case PLANT -> trumpetVine();
            case BOSS -> salamanderMonarch();
            case VILLAGER -> throw new IllegalArgumentException("Villager uses ToadModel");
        };
    }

    private static MeshDefinition emptyMesh() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        for (String name : PARTS) {
            root.addOrReplaceChild(name, CubeListBuilder.create(), PartPose.ZERO);
        }
        return mesh;
    }

    private static LayerDefinition finish(MeshDefinition mesh) {
        return LayerDefinition.create(mesh, 128, 128);
    }

    private static CubeListBuilder box(int u, int v, float x, float y, float z,
                                       float width, float height, float depth) {
        return CubeListBuilder.create().texOffs(u, v).addBox(x, y, z, width, height, depth);
    }

    private static PartPose pose(float x, float y, float z) {
        return PartPose.offset(x, y, z);
    }

    private static PartPose pose(float x, float y, float z, float xr, float yr, float zr) {
        return PartPose.offsetAndRotation(x, y, z, xr, yr, zr);
    }

    private static LayerDefinition sproutling() { // Goomba
        MeshDefinition mesh = emptyMesh();
        PartDefinition r = mesh.getRoot();
        r.addOrReplaceChild("body", box(0, 0, -5, -5, -5, 10, 10, 10), pose(0, 14, 0));
        r.addOrReplaceChild("left_leg", box(0, 40, -1, 0, -3, 4, 3, 6), pose(2, 21, 0));
        r.addOrReplaceChild("right_leg", box(0, 40, -3, 0, -3, 4, 3, 6), pose(-2, 21, 0));
        return finish(mesh);
    }

    private static LayerDefinition gecko() { // Koopa
        MeshDefinition mesh = emptyMesh();
        PartDefinition r = mesh.getRoot();
        r.addOrReplaceChild("body", box(0, 16, -4, 0, -2, 8, 10, 4), pose(0, 4, 0));
        r.addOrReplaceChild("shell", box(64, 0, -5, 1, 2, 10, 12, 6), pose(0, 4, 0));
        r.addOrReplaceChild("head", box(0, 0, -4, -4, -4, 8, 8, 8), pose(0, 4, -2));
        r.addOrReplaceChild("left_arm", box(32, 48, -1, -1, -2, 3, 8, 3), pose(5, 6, 0));
        r.addOrReplaceChild("right_arm", box(32, 48, -2, -1, -2, 3, 8, 3), pose(-5, 6, 0));
        r.addOrReplaceChild("left_leg", box(0, 48, -2, 0, -2, 4, 10, 4), pose(2, 14, 0));
        r.addOrReplaceChild("right_leg", box(0, 48, -2, 0, -2, 4, 10, 4), pose(-2, 14, 0));
        return finish(mesh);
    }

    private static LayerDefinition crusher() { // Thwomp
        MeshDefinition mesh = emptyMesh();
        PartDefinition r = mesh.getRoot();
        r.addOrReplaceChild("body", box(0, 0, -8, -8, -8, 16, 16, 16), pose(0, 8, 0));
        return finish(mesh);
    }

    private static LayerDefinition torpedoMoth() { // Bullet Bill
        MeshDefinition mesh = emptyMesh();
        PartDefinition r = mesh.getRoot();
        r.addOrReplaceChild("body", box(0, 0, -7, -7, -8, 14, 14, 16), pose(0, 17, 0));
        r.addOrReplaceChild("left_arm", box(64, 0, 0, -2, -3, 2, 4, 6), pose(7, 17, -2));
        r.addOrReplaceChild("right_arm", box(64, 0, -2, -2, -3, 2, 4, 6), pose(-7, 17, -2));
        return finish(mesh);
    }

    private static LayerDefinition moonWisp() { // Boo
        MeshDefinition mesh = emptyMesh();
        PartDefinition r = mesh.getRoot();
        r.addOrReplaceChild("body", box(0, 0, -6, -6, -6, 12, 12, 12), pose(0, 14, 0));
        r.addOrReplaceChild("left_arm", box(64, 0, -2, -2, -3, 4, 4, 6), pose(7, 13, -3));
        r.addOrReplaceChild("right_arm", box(64, 0, -2, -2, -3, 4, 4, 6), pose(-7, 13, -3));
        r.addOrReplaceChild("tail", box(64, 16, -3, -3, 0, 6, 6, 6), pose(0, 17, 6));
        return finish(mesh);
    }

    private static LayerDefinition mantaRider() { // Lakitu
        MeshDefinition mesh = emptyMesh();
        PartDefinition r = mesh.getRoot();
        r.addOrReplaceChild("shell", box(64, 0, -12, -4, -12, 24, 8, 24), pose(0, 20, 0)); // Cloud
        r.addOrReplaceChild("body", box(0, 16, -4, 0, -2, 8, 8, 4), pose(0, 8, 0));
        r.addOrReplaceChild("head", box(0, 0, -4, -4, -4, 8, 8, 8), pose(0, 8, -2));
        r.addOrReplaceChild("left_arm", box(32, 48, -1, -1, -2, 3, 8, 3), pose(5, 10, 0, -0.5F, 0, 0));
        r.addOrReplaceChild("right_arm", box(32, 48, -2, -1, -2, 3, 8, 3), pose(-5, 10, 0, -0.5F, 0, 0));
        return finish(mesh);
    }

    private static LayerDefinition pangolin() { // Hammer Bro
        MeshDefinition mesh = emptyMesh();
        PartDefinition r = mesh.getRoot();
        r.addOrReplaceChild("body", box(0, 16, -4, 0, -2, 8, 10, 4), pose(0, 4, 0));
        r.addOrReplaceChild("shell", box(64, 0, -5, 1, 2, 10, 12, 6), pose(0, 4, 0));
        r.addOrReplaceChild("head", box(0, 0, -4, -4, -4, 8, 8, 8), pose(0, 4, -2));
        r.addOrReplaceChild("left_arm", box(32, 48, -1, -1, -2, 3, 8, 3), pose(5, 6, 0));
        r.addOrReplaceChild("right_arm", box(32, 48, -2, -1, -2, 3, 8, 3), pose(-5, 6, 0));
        r.addOrReplaceChild("left_leg", box(0, 48, -2, 0, -2, 4, 10, 4), pose(2, 14, 0));
        r.addOrReplaceChild("right_leg", box(0, 48, -2, 0, -2, 4, 10, 4), pose(-2, 14, 0));
        return finish(mesh);
    }

    private static LayerDefinition pincushionCrab() { // Spiny
        MeshDefinition mesh = emptyMesh();
        PartDefinition r = mesh.getRoot();
        r.addOrReplaceChild("body", box(0, 0, -6, -6, -6, 12, 10, 12), pose(0, 17, 0)); // Spiked shell
        r.addOrReplaceChild("head", box(0, 32, -4, -3, -4, 8, 6, 6), pose(0, 17, -6));
        r.addOrReplaceChild("left_arm", box(0, 48, -1.5F, 0, -1.5F, 3, 6, 3), pose(4, 18, -4)); // front left
        r.addOrReplaceChild("right_arm", box(0, 48, -1.5F, 0, -1.5F, 3, 6, 3), pose(-4, 18, -4)); // front right
        r.addOrReplaceChild("left_leg", box(0, 48, -1.5F, 0, -1.5F, 3, 6, 3), pose(4, 18, 4)); // back left
        r.addOrReplaceChild("right_leg", box(0, 48, -1.5F, 0, -1.5F, 3, 6, 3), pose(-4, 18, 4)); // back right
        return finish(mesh);
    }

    private static LayerDefinition burrowingBeetle() { // Buzzy Beetle
        MeshDefinition mesh = emptyMesh();
        PartDefinition r = mesh.getRoot();
        r.addOrReplaceChild("body", box(0, 0, -6, -6, -6, 12, 10, 12), pose(0, 17, 0));
        r.addOrReplaceChild("head", box(0, 32, -4, -3, -4, 8, 6, 6), pose(0, 17, -6));
        r.addOrReplaceChild("left_arm", box(0, 48, -1.5F, 0, -1.5F, 3, 6, 3), pose(4, 18, -4));
        r.addOrReplaceChild("right_arm", box(0, 48, -1.5F, 0, -1.5F, 3, 6, 3), pose(-4, 18, -4));
        r.addOrReplaceChild("left_leg", box(0, 48, -1.5F, 0, -1.5F, 3, 6, 3), pose(4, 18, 4));
        r.addOrReplaceChild("right_leg", box(0, 48, -1.5F, 0, -1.5F, 3, 6, 3), pose(-4, 18, 4));
        return finish(mesh);
    }

    private static LayerDefinition trumpetVine() { // Piranha Plant
        MeshDefinition mesh = emptyMesh();
        PartDefinition r = mesh.getRoot();
        r.addOrReplaceChild("body", box(0, 0, -2, -12, -2, 4, 12, 4), pose(0, 24, 0)); // Stem
        r.addOrReplaceChild("head", box(0, 32, -6, -10, -6, 12, 12, 12), pose(0, 12, 0, -0.3F, 0, 0)); // Big head
        r.addOrReplaceChild("left_arm", box(0, 16, 0, 0, -3, 8, 0, 6), pose(2, 22, 0, 0, 0, 0.5F)); // Leaf
        r.addOrReplaceChild("right_arm", box(0, 16, -8, 0, -3, 8, 0, 6), pose(-2, 22, 0, 0, 0, -0.5F)); // Leaf
        return finish(mesh);
    }

    private static LayerDefinition salamanderMonarch() { // Bowser
        MeshDefinition mesh = emptyMesh();
        PartDefinition r = mesh.getRoot();
        r.addOrReplaceChild("body", box(0, 0, -8, -6, -6, 16, 14, 12), pose(0, 4, 0, 0.2F, 0, 0)); // Big torso
        r.addOrReplaceChild("shell", box(64, 0, -10, -8, 6, 20, 18, 8), pose(0, 4, 0, 0.2F, 0, 0)); // Spiked shell
        r.addOrReplaceChild("head", box(0, 32, -6, -6, -8, 12, 12, 12), pose(0, -3, -6));
        r.addOrReplaceChild("left_arm", box(48, 48, -2, -2, -3, 6, 14, 6), pose(8, 2, -4, -0.3F, 0, -0.2F));
        r.addOrReplaceChild("right_arm", box(48, 48, -4, -2, -3, 6, 14, 6), pose(-8, 2, -4, -0.3F, 0, 0.2F));
        r.addOrReplaceChild("left_leg", box(0, 48, -4, 0, -4, 8, 12, 8), pose(6, 12, 2));
        r.addOrReplaceChild("right_leg", box(0, 48, -4, 0, -4, 8, 12, 8), pose(-6, 12, 2));
        r.addOrReplaceChild("tail", box(64, 48, -3, 0, -3, 6, 10, 6), pose(0, 14, 6, 0.6F, 0, 0));
        return finish(mesh);
    }

    @Override
    public void setupAnim(CourseEnemyRenderState state) {
        super.setupAnim(state);
        float speed = Math.min(1.0F, state.walkAnimationSpeed);
        float phase = state.walkAnimationPos * 0.72F;
        float step = Mth.cos(phase) * 0.9F * speed;
        float opposite = Mth.cos(phase + Mth.PI) * 0.9F * speed;
        float idle = Mth.sin(state.ageInTicks * 0.11F);

        head.yRot = state.yRot * Mth.DEG_TO_RAD * 0.55F;
        head.xRot += state.xRot * Mth.DEG_TO_RAD * 0.35F;

        switch (profile) {
            case SPROUTLING -> {
                leftLeg.xRot = opposite;
                rightLeg.xRot = step;
                body.y += Math.abs(Mth.sin(phase)) * speed * -0.8F + idle * 0.12F;
            }
            case GECKO -> {
                walk(step, opposite, 0.75F);
            }
            case CRUSHER -> {
            }
            case FLYER -> {
            }
            case WISP -> {
                body.y += idle * 0.8F;
                leftArm.zRot += idle * 0.15F;
                rightArm.zRot -= idle * 0.15F;
                tail.yRot = Mth.sin(state.ageInTicks * 0.15F) * 0.2F;
            }
            case RIDER -> {
                leftArm.xRot = -0.5F;
                rightArm.xRot = -0.5F;
            }
            case WARRIOR -> {
                walk(step, opposite, 0.82F);
            }
            case CRAWLER, BEETLE -> {
                leftArm.yRot = step * 0.16F;
                rightArm.yRot = -step * 0.16F;
                leftLeg.yRot = -opposite * 0.16F;
                rightLeg.yRot = opposite * 0.16F;
                body.y += Math.abs(Mth.sin(phase * 1.35F)) * speed * -0.18F;
            }
            case PLANT -> {
                head.xRot = -0.3F + Mth.sin(state.ageInTicks * 0.11F + 0.6F) * 0.09F;
                leftArm.zRot = 0.5F + idle * 0.12F;
                rightArm.zRot = -0.5F - idle * 0.12F;
            }
            case BOSS -> {
                walk(step, opposite, 0.42F);
                body.y += Math.abs(Mth.sin(phase)) * speed * -0.22F;
                tail.yRot = Mth.sin(state.ageInTicks * 0.08F) * 0.16F;
                shell.xRot = idle * 0.012F;
            }
            case VILLAGER -> {}
        }
    }

    private void walk(float step, float opposite, float armScale) {
        rightLeg.xRot = step;
        leftLeg.xRot = opposite;
        rightArm.xRot = -step * armScale;
        leftArm.xRot = -opposite * armScale;
    }
}
