package com.studio.planeshift.client.render;

import com.studio.planeshift.common.entity.EnemyRigProfile;
import com.studio.planeshift.PlaneShift;
import java.util.EnumMap;
import java.util.Map;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.util.Mth;

/**
 * Production low-poly geometry for the PlaneShift enemy cast.
 *
 * <p>Every {@link EnemyRigProfile} owns a different baked mesh.  The old shared rig changed only
 * scale and visibility, which meant a plant, beetle and monarch were recognisably the same biped.
 * These layers follow the original turnarounds in {@code tools/art_sources}: leaves are modelled
 * leaves, shells have volume, crawlers have six legs, the torpedo is horizontal, and the boss has
 * a separate jaw, horns, mantle and tail.  The common class only shares animation plumbing.
 *
 * <p>All sheets are 128x128.  Broad material families occupy stable quadrants so the exact UV
 * images can be regenerated by {@code tools/EnemyTextureGen.java} without Blockbench at build
 * time.  Runtime remains dependency-free.
 */
public final class BespokeEnemyModel extends EntityModel<CourseEnemyRenderState> {

    private static final Map<EnemyRigProfile, ModelLayerLocation> LAYERS = new EnumMap<>(EnemyRigProfile.class);

    static {
        for (EnemyRigProfile profile : EnemyRigProfile.values()) {
            if (profile != EnemyRigProfile.VILLAGER) {
                LAYERS.put(profile, new ModelLayerLocation(
                        PlaneShift.id("enemy/" + profile.name().toLowerCase()), "main"));
            }
        }
    }

    private static final String[] PARTS = {
        "body", "head", "jaw", "snout", "shell", "left_arm", "right_arm",
        "left_leg", "right_leg", "left_wing", "right_wing", "tail", "tail_tip",
        "detail_1", "detail_2", "detail_3", "detail_4", "detail_5", "detail_6"
    };

    private final EnemyRigProfile profile;
    private final ModelPart body;
    private final ModelPart head;
    private final ModelPart jaw;
    private final ModelPart snout;
    private final ModelPart shell;
    private final ModelPart leftArm;
    private final ModelPart rightArm;
    private final ModelPart leftLeg;
    private final ModelPart rightLeg;
    private final ModelPart leftWing;
    private final ModelPart rightWing;
    private final ModelPart tail;
    private final ModelPart tailTip;
    private final ModelPart[] details;

    public BespokeEnemyModel(ModelPart root, EnemyRigProfile profile) {
        super(root);
        this.profile = profile;
        body = root.getChild("body");
        head = root.getChild("head");
        jaw = root.getChild("jaw");
        snout = root.getChild("snout");
        shell = root.getChild("shell");
        leftArm = root.getChild("left_arm");
        rightArm = root.getChild("right_arm");
        leftLeg = root.getChild("left_leg");
        rightLeg = root.getChild("right_leg");
        leftWing = root.getChild("left_wing");
        rightWing = root.getChild("right_wing");
        tail = root.getChild("tail");
        tailTip = root.getChild("tail_tip");
        details = new ModelPart[] {
            root.getChild("detail_1"), root.getChild("detail_2"), root.getChild("detail_3"),
            root.getChild("detail_4"), root.getChild("detail_5"), root.getChild("detail_6")
        };
    }

    public static ModelLayerLocation layer(EnemyRigProfile profile) {
        ModelLayerLocation location = LAYERS.get(profile);
        if (location == null) {
            throw new IllegalArgumentException("No enemy layer for " + profile);
        }
        return location;
    }

    public static LayerDefinition createLayer(EnemyRigProfile profile) {
        return switch (profile) {
            case SPROUTLING -> sproutling();
            case GECKO -> gecko();
            case CRUSHER -> crusher();
            case FLYER -> torpedoMoth();
            case WISP -> moonWisp();
            case RIDER -> mantaRider();
            case WARRIOR -> pangolin();
            case CRAWLER -> pincushionCrab();
            case BEETLE -> burrowingBeetle();
            case PLANT -> trumpetVine();
            case BOSS -> salamanderMonarch();
            case VILLAGER -> throw new IllegalArgumentException("Villager uses ToadModel");
        };
    }

    private static MeshDefinition emptyMesh() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        for (String name : PARTS) {
            root.addOrReplaceChild(name, CubeListBuilder.create(), PartPose.ZERO);
        }
        return mesh;
    }

    private static LayerDefinition finish(MeshDefinition mesh) {
        return LayerDefinition.create(mesh, 128, 128);
    }

    private static CubeListBuilder box(int u, int v, float x, float y, float z,
                                       float width, float height, float depth) {
        return CubeListBuilder.create().texOffs(u, v).addBox(x, y, z, width, height, depth);
    }

    private static PartPose pose(float x, float y, float z) {
        return PartPose.offset(x, y, z);
    }

    private static PartPose pose(float x, float y, float z, float xr, float yr, float zr) {
        return PartPose.offsetAndRotation(x, y, z, xr, yr, zr);
    }

    private static LayerDefinition sproutling() {
        MeshDefinition mesh = emptyMesh();
        PartDefinition r = mesh.getRoot();
        r.addOrReplaceChild("body", box(0, 0, -6, -9, -4, 12, 9, 8), pose(0, 21, 0));
        r.addOrReplaceChild("head", box(0, 80, -5, -3, -0.5F, 10, 6, 1), pose(0, 16, -4));
        r.addOrReplaceChild("left_leg", box(0, 40, -4.5F, 0, -3.5F, 5, 3, 7), pose(0, 21, 0));
        r.addOrReplaceChild("right_leg", box(0, 40, -0.5F, 0, -3.5F, 5, 3, 7), pose(0, 21, 0));
        r.addOrReplaceChild("detail_1", box(64, 40, -1.5F, -8, -0.5F, 3, 8, 1), pose(0, 13, 0));
        r.addOrReplaceChild("detail_2", box(64, 40, -1, -7, -0.5F, 2, 7, 1),
                pose(-3, 14, 0, 0, 0, -0.82F));
        r.addOrReplaceChild("detail_3", box(64, 40, -1, -7, -0.5F, 2, 7, 1),
                pose(3, 14, 0, 0, 0, 0.82F));
        return finish(mesh);
    }

    private static LayerDefinition gecko() {
        MeshDefinition mesh = emptyMesh();
        PartDefinition r = mesh.getRoot();
        r.addOrReplaceChild("body", box(0, 0, -4, -8, -3, 8, 8, 6), pose(0, 18, 0));
        r.addOrReplaceChild("head", box(64, 0, -4, -6, -4, 8, 6, 7), pose(0, 11, 0));
        r.addOrReplaceChild("snout", box(0, 80, -3, -2, -4, 6, 3, 4), pose(0, 9, -3));
        r.addOrReplaceChild("shell", box(64, 40, -4, -5, -1, 8, 10, 3), pose(0, 14, 3));
        r.addOrReplaceChild("left_arm", box(0, 40, 0, 0, -1.5F, 3, 7, 3), pose(4, 11, 0, 0, 0, -0.12F));
        r.addOrReplaceChild("right_arm", box(0, 40, -3, 0, -1.5F, 3, 7, 3), pose(-4, 11, 0, 0, 0, 0.12F));
        r.addOrReplaceChild("left_leg", box(0, 40, -1.5F, 0, -2, 3, 6, 4), pose(2.5F, 18, 0));
        r.addOrReplaceChild("right_leg", box(0, 40, -1.5F, 0, -2, 3, 6, 4), pose(-2.5F, 18, 0));
        r.addOrReplaceChild("tail", box(64, 40, -2, -2, 0, 4, 4, 8), pose(0, 17, 3, 0.35F, 0, 0));
        r.addOrReplaceChild("tail_tip", box(64, 40, -1.5F, -1.5F, 0, 3, 3, 7), pose(0, 19, 10, 0.62F, 0, 0));
        r.addOrReplaceChild("detail_1", box(64, 80, -1.5F, -1.5F, -1, 3, 3, 2), pose(-2.7F, 8.5F, -3.5F));
        r.addOrReplaceChild("detail_2", box(64, 80, -1.5F, -1.5F, -1, 3, 3, 2), pose(2.7F, 8.5F, -3.5F));
        return finish(mesh);
    }

    private static LayerDefinition crusher() {
        MeshDefinition mesh = emptyMesh();
        PartDefinition r = mesh.getRoot();
        r.addOrReplaceChild("body", box(0, 0, -8, -14, -4, 16, 14, 8), pose(0, 21, 0));
        r.addOrReplaceChild("head", box(0, 80, -5, -4, -0.5F, 10, 7, 1), pose(0, 12, -4));
        r.addOrReplaceChild("left_arm", box(64, 0, -1, -4, -3, 6, 8, 6), pose(8, 13, 0));
        r.addOrReplaceChild("right_arm", box(64, 0, -5, -4, -3, 6, 8, 6), pose(-8, 13, 0));
        r.addOrReplaceChild("left_leg", box(0, 40, -2, 0, -2.5F, 4, 4, 5), pose(4, 21, 0));
        r.addOrReplaceChild("right_leg", box(0, 40, -2, 0, -2.5F, 4, 4, 5), pose(-4, 21, 0));
        r.addOrReplaceChild("detail_1", box(64, 80, -3, -3, -0.5F, 6, 6, 1), pose(0, 18, -4.1F));
        r.addOrReplaceChild("detail_2", box(64, 40, -2, -2, -1, 4, 4, 2), pose(0, 8, 0));
        return finish(mesh);
    }

    private static LayerDefinition torpedoMoth() {
        MeshDefinition mesh = emptyMesh();
        PartDefinition r = mesh.getRoot();
        r.addOrReplaceChild("body", box(0, 0, -4, -4, -8, 8, 8, 16), pose(0, 15, 0));
        r.addOrReplaceChild("head", box(64, 0, -5, -5, -4, 10, 10, 5), pose(0, 15, -8));
        r.addOrReplaceChild("snout", box(0, 80, -4, -3, -2, 8, 6, 2), pose(0, 15, -12));
        r.addOrReplaceChild("left_wing", box(64, 40, 0, -1, -4, 10, 2, 7), pose(3, 13, 0, 0, -0.16F, -0.38F));
        r.addOrReplaceChild("right_wing", box(64, 40, -10, -1, -4, 10, 2, 7), pose(-3, 13, 0, 0, 0.16F, 0.38F));
        r.addOrReplaceChild("left_arm", box(64, 40, 0, -1, -3, 7, 2, 5), pose(3, 17, 1, 0, 0.2F, 0.24F));
        r.addOrReplaceChild("right_arm", box(64, 40, -7, -1, -3, 7, 2, 5), pose(-3, 17, 1, 0, -0.2F, -0.24F));
        r.addOrReplaceChild("tail", box(0, 40, -1.5F, -5, 0, 3, 10, 4), pose(0, 15, 8));
        r.addOrReplaceChild("detail_1", box(64, 80, -1, -2, -1, 2, 4, 2), pose(-2.2F, 14.5F, -12.8F));
        r.addOrReplaceChild("detail_2", box(64, 80, -1, -2, -1, 2, 4, 2), pose(2.2F, 14.5F, -12.8F));
        return finish(mesh);
    }

    private static LayerDefinition moonWisp() {
        MeshDefinition mesh = emptyMesh();
        PartDefinition r = mesh.getRoot();
        r.addOrReplaceChild("body", box(0, 0, -6, -6, -5, 12, 10, 10), pose(0, 14, 0));
        r.addOrReplaceChild("head", box(0, 80, -4, -3, -0.5F, 8, 5, 1), pose(0, 13, -5));
        for (int i = 0; i < 6; i++) {
            float x = -4.5F + i * 1.8F;
            int height = 4 + (i % 3);
            r.addOrReplaceChild("detail_" + (i + 1), box(64, 40, -0.75F, 0, -0.75F, 1.5F, height, 1.5F),
                    pose(x, 18, 0, 0, 0, (i - 2.5F) * 0.04F));
        }
        r.addOrReplaceChild("left_arm", box(64, 80, -1, -1, -1, 2, 2, 2), pose(8, 15, 0));
        r.addOrReplaceChild("right_arm", box(64, 80, -1, -1, -1, 2, 2, 2), pose(-8, 15, 0));
        return finish(mesh);
    }

    private static LayerDefinition mantaRider() {
        MeshDefinition mesh = emptyMesh();
        PartDefinition r = mesh.getRoot();
        r.addOrReplaceChild("body", box(0, 0, -7, -2, -5, 14, 4, 10), pose(0, 20, 0));
        r.addOrReplaceChild("left_wing", box(0, 0, 0, -1, -5, 9, 2, 10), pose(6, 20, 0, 0, 0, -0.08F));
        r.addOrReplaceChild("right_wing", box(0, 0, -9, -1, -5, 9, 2, 10), pose(-6, 20, 0, 0, 0, 0.08F));
        r.addOrReplaceChild("tail", box(0, 40, -1.5F, -1.5F, 0, 3, 3, 9), pose(0, 20, 5, 0.16F, 0, 0));
        r.addOrReplaceChild("shell", box(64, 40, -4, -5, -3, 8, 5, 6), pose(0, 17, 0));
        r.addOrReplaceChild("head", box(64, 0, -3.5F, -6, -3, 7, 6, 6), pose(0, 12, 0));
        r.addOrReplaceChild("snout", box(0, 80, -2.5F, -2, -2, 5, 3, 2), pose(0, 10, -3));
        r.addOrReplaceChild("left_arm", box(0, 40, 0, 0, -1, 2, 5, 2), pose(3.5F, 13, 0, -0.65F, 0, -0.25F));
        r.addOrReplaceChild("right_arm", box(0, 40, -2, 0, -1, 2, 5, 2), pose(-3.5F, 13, 0, -0.65F, 0, 0.25F));
        r.addOrReplaceChild("detail_1", box(64, 80, -3, -1, -0.5F, 6, 2, 1), pose(0, 8.5F, -3.1F));
        r.addOrReplaceChild("detail_2", box(64, 40, 0, -0.5F, -0.5F, 8, 1, 1), pose(2, 13, 2, 0, 0.35F, 0.12F));
        return finish(mesh);
    }

    private static LayerDefinition pangolin() {
        MeshDefinition mesh = emptyMesh();
        PartDefinition r = mesh.getRoot();
        r.addOrReplaceChild("body", box(0, 0, -5, -9, -3.5F, 10, 9, 7), pose(0, 19, 0));
        r.addOrReplaceChild("shell", box(64, 40, -5.5F, -8, -1, 11, 10, 4), pose(0, 17, 2));
        r.addOrReplaceChild("head", box(64, 0, -4, -6, -4, 8, 6, 7), pose(0, 10, 0));
        r.addOrReplaceChild("snout", box(0, 80, -3, -2, -4, 6, 3, 4), pose(0, 9, -3));
        r.addOrReplaceChild("left_arm", box(0, 40, 0, 0, -2, 4, 8, 4), pose(5, 11, 0, 0, 0, -0.18F));
        r.addOrReplaceChild("right_arm", box(0, 40, -4, 0, -2, 4, 8, 4), pose(-5, 11, 0, 0, 0, 0.18F));
        r.addOrReplaceChild("left_leg", box(0, 40, -2, 0, -2.5F, 4, 5, 5), pose(3, 19, 0));
        r.addOrReplaceChild("right_leg", box(0, 40, -2, 0, -2.5F, 4, 5, 5), pose(-3, 19, 0));
        r.addOrReplaceChild("tail", box(64, 40, -3, -3, 0, 6, 6, 8), pose(0, 17, 3, 0.42F, 0, 0));
        r.addOrReplaceChild("tail_tip", box(64, 40, -2, -2, 0, 4, 4, 7), pose(0, 20, 10, 0.62F, 0, 0));
        r.addOrReplaceChild("detail_1", box(64, 80, -4.5F, -1, -0.5F, 9, 2, 1), pose(0, 6, -3.8F));
        return finish(mesh);
    }

    private static LayerDefinition pincushionCrab() {
        MeshDefinition mesh = emptyMesh();
        PartDefinition r = mesh.getRoot();
        r.addOrReplaceChild("body", box(0, 0, -7, -5, -5, 14, 7, 10), pose(0, 18, 0));
        r.addOrReplaceChild("head", box(0, 80, -4, -2, -0.5F, 8, 4, 1), pose(0, 17, -5));
        r.addOrReplaceChild("left_arm", box(64, 0, 0, -2, -2, 6, 5, 5), pose(7, 19, -2, 0, 0, -0.18F));
        r.addOrReplaceChild("right_arm", box(64, 0, -6, -2, -2, 6, 5, 5), pose(-7, 19, -2, 0, 0, 0.18F));
        for (int i = 0; i < 6; i++) {
            boolean left = i >= 3;
            int lane = i % 3;
            float x = left ? 6 : -6;
            float z = -3 + lane * 3;
            r.addOrReplaceChild("detail_" + (i + 1), box(0, 40, left ? 0 : -5, -1, -1, 5, 2, 2),
                    pose(x, 21, z, 0, (lane - 1) * 0.2F, left ? 0.32F : -0.32F));
        }
        r.addOrReplaceChild("left_leg", box(64, 80, -1, -5, -1, 2, 5, 2), pose(4, 14, -1, -0.3F, 0, 0.35F));
        r.addOrReplaceChild("right_leg", box(64, 80, -1, -5, -1, 2, 5, 2), pose(-4, 14, -1, -0.3F, 0, -0.35F));
        r.addOrReplaceChild("tail", box(64, 80, -1, -6, -1, 2, 6, 2), pose(0, 14, 1, 0.25F, 0, 0));
        r.addOrReplaceChild("tail_tip", box(64, 80, -1, -5, -1, 2, 5, 2), pose(0, 15, -3, -0.35F, 0, 0));
        return finish(mesh);
    }

    private static LayerDefinition burrowingBeetle() {
        MeshDefinition mesh = emptyMesh();
        PartDefinition r = mesh.getRoot();
        r.addOrReplaceChild("body", box(0, 0, -7, -5, -7, 14, 8, 14), pose(0, 18, 1));
        r.addOrReplaceChild("shell", box(64, 40, -6, -3, -6, 12, 5, 13), pose(0, 15, 2));
        r.addOrReplaceChild("head", box(64, 0, -5, -4, -5, 10, 7, 7), pose(0, 19, -6));
        r.addOrReplaceChild("snout", box(0, 80, -4, -1.5F, -2, 8, 3, 2), pose(0, 20, -11));
        for (int i = 0; i < 6; i++) {
            boolean left = i >= 3;
            int lane = i % 3;
            float x = left ? 6 : -6;
            float z = -3 + lane * 4;
            r.addOrReplaceChild("detail_" + (i + 1), box(0, 40, left ? 0 : -5, -1, -1, 5, 2, 2),
                    pose(x, 21, z, 0, (lane - 1) * 0.18F, left ? 0.38F : -0.38F));
        }
        r.addOrReplaceChild("left_arm", box(64, 80, 0, -1, -1, 4, 2, 2), pose(2, 21, -11, 0, -0.32F, 0.18F));
        r.addOrReplaceChild("right_arm", box(64, 80, -4, -1, -1, 4, 2, 2), pose(-2, 21, -11, 0, 0.32F, -0.18F));
        return finish(mesh);
    }

    private static LayerDefinition trumpetVine() {
        MeshDefinition mesh = emptyMesh();
        PartDefinition r = mesh.getRoot();
        r.addOrReplaceChild("shell", box(64, 40, -6, -3, -5, 12, 5, 10), pose(0, 22, 0));
        r.addOrReplaceChild("body", box(0, 0, -3, -13, -3, 6, 13, 6), pose(0, 21, 0));
        r.addOrReplaceChild("head", box(64, 0, -6, -6, -5, 12, 7, 10), pose(0, 7, 0, -0.08F, 0, 0));
        r.addOrReplaceChild("jaw", box(64, 0, -6, -1, -5, 12, 5, 10), pose(0, 8, 0, 0.18F, 0, 0));
        r.addOrReplaceChild("snout", box(0, 80, -5, -4, -0.5F, 10, 8, 1), pose(0, 7, -5));
        r.addOrReplaceChild("left_arm", box(0, 40, 0, -1, -3, 8, 2, 6), pose(2.5F, 16, 0, 0, 0, 0.38F));
        r.addOrReplaceChild("right_arm", box(0, 40, -8, -1, -3, 8, 2, 6), pose(-2.5F, 16, 0, 0, 0, -0.38F));
        r.addOrReplaceChild("detail_1", box(64, 80, -1, -3, -1, 2, 3, 2), pose(-3.5F, 5, -4.5F));
        r.addOrReplaceChild("detail_2", box(64, 80, -1, -3, -1, 2, 3, 2), pose(0, 4, -4.5F));
        r.addOrReplaceChild("detail_3", box(64, 80, -1, -3, -1, 2, 3, 2), pose(3.5F, 5, -4.5F));
        r.addOrReplaceChild("detail_4", box(64, 80, -1, 0, -1, 2, 3, 2), pose(-3.5F, 10, -4.5F));
        r.addOrReplaceChild("detail_5", box(64, 80, -1, 0, -1, 2, 3, 2), pose(0, 11, -4.5F));
        r.addOrReplaceChild("detail_6", box(64, 80, -1, 0, -1, 2, 3, 2), pose(3.5F, 10, -4.5F));
        return finish(mesh);
    }

    private static LayerDefinition salamanderMonarch() {
        MeshDefinition mesh = emptyMesh();
        PartDefinition r = mesh.getRoot();
        r.addOrReplaceChild("body", box(0, 0, -8, -13, -5, 16, 13, 10), pose(0, 20, 0));
        r.addOrReplaceChild("shell", box(64, 40, -9, -12, -2, 18, 14, 6), pose(0, 17, 4));
        r.addOrReplaceChild("head", box(64, 0, -6, -8, -6, 12, 8, 10), pose(0, 7, -1));
        r.addOrReplaceChild("snout", box(0, 80, -5, -3, -6, 10, 5, 6), pose(0, 4, -6));
        r.addOrReplaceChild("jaw", box(0, 80, -5, -1, -6, 10, 4, 6), pose(0, 7, -6, 0.1F, 0, 0));
        r.addOrReplaceChild("left_arm", box(0, 40, 0, -3, -3, 6, 13, 6), pose(8, 9, 0, -0.12F, 0, -0.22F));
        r.addOrReplaceChild("right_arm", box(0, 40, -6, -3, -3, 6, 13, 6), pose(-8, 9, 0, -0.12F, 0, 0.22F));
        r.addOrReplaceChild("left_leg", box(0, 40, -3, -2, -4, 6, 8, 8), pose(6, 18, 0));
        r.addOrReplaceChild("right_leg", box(0, 40, -3, -2, -4, 6, 8, 8), pose(-6, 18, 0));
        r.addOrReplaceChild("tail", box(64, 40, -4, -4, 0, 8, 8, 12), pose(0, 17, 5, 0.35F, 0, 0));
        r.addOrReplaceChild("tail_tip", box(64, 40, -3, -3, 0, 6, 6, 11), pose(0, 20, 15, 0.5F, 0, 0));
        r.addOrReplaceChild("detail_1", box(64, 80, -1.5F, -7, -1.5F, 3, 7, 3), pose(-4, 0, -2, 0, 0, -0.3F));
        r.addOrReplaceChild("detail_2", box(64, 80, -1.5F, -7, -1.5F, 3, 7, 3), pose(4, 0, -2, 0, 0, 0.3F));
        r.addOrReplaceChild("detail_3", box(64, 80, -1.5F, -6, -1.5F, 3, 6, 3), pose(0, 4, 8, -0.4F, 0, 0));
        r.addOrReplaceChild("detail_4", box(64, 80, -1.5F, -6, -1.5F, 3, 6, 3), pose(0, 8, 10, -0.2F, 0, 0));
        r.addOrReplaceChild("detail_5", box(64, 80, -1.5F, -5, -1.5F, 3, 5, 3), pose(0, 12, 11, 0, 0, 0));
        return finish(mesh);
    }

    @Override
    public void setupAnim(CourseEnemyRenderState state) {
        super.setupAnim(state);
        float speed = Math.min(1.0F, state.walkAnimationSpeed);
        float phase = state.walkAnimationPos * 0.72F;
        float step = Mth.cos(phase) * 0.9F * speed;
        float opposite = Mth.cos(phase + Mth.PI) * 0.9F * speed;
        float idle = Mth.sin(state.ageInTicks * 0.11F);

        head.yRot = state.yRot * Mth.DEG_TO_RAD * 0.55F;
        head.xRot += state.xRot * Mth.DEG_TO_RAD * 0.35F;

        switch (profile) {
            case SPROUTLING -> {
                leftLeg.xRot = opposite;
                rightLeg.xRot = step;
                body.y += Math.abs(Mth.sin(phase)) * speed * -0.8F + idle * 0.12F;
                details[0].zRot += idle * 0.08F;
                details[1].zRot += idle * 0.06F;
                details[2].zRot -= idle * 0.06F;
            }
            case GECKO -> {
                walk(step, opposite, 0.75F);
                tail.yRot = Mth.sin(state.ageInTicks * 0.13F) * 0.22F - step * 0.12F;
                tailTip.yRot = tail.yRot * 1.35F;
            }
            case CRUSHER -> {
                body.y += idle * 0.3F;
                float slam = Math.max(0, Mth.sin(state.ageInTicks * 0.12F) - 0.68F) * 2.7F;
                leftArm.y += slam * 4.2F;
                rightArm.y += slam * 4.2F;
                leftLeg.y += slam * 2.5F;
                rightLeg.y += slam * 2.5F;
            }
            case FLYER -> {
                body.y += idle * 0.3F;
                float flap = Mth.sin(state.ageInTicks * 0.9F) * 0.48F;
                leftWing.zRot += flap;
                rightWing.zRot -= flap;
                leftArm.zRot -= flap * 0.65F;
                rightArm.zRot += flap * 0.65F;
                tail.yRot = Mth.sin(state.ageInTicks * 0.18F) * 0.08F;
            }
            case WISP -> {
                body.y += idle * 0.8F;
                head.y += idle * 0.8F;
                leftArm.y += -idle * 0.35F;
                rightArm.y += idle * 0.35F;
                for (int i = 0; i < details.length; i++) {
                    details[i].xRot = Mth.sin(state.ageInTicks * 0.16F + i * 0.7F) * 0.12F;
                }
            }
            case RIDER -> {
                float flap = Mth.sin(state.ageInTicks * 0.32F) * 0.22F;
                leftWing.zRot += flap;
                rightWing.zRot -= flap;
                leftArm.xRot += -flap * 0.7F;
                rightArm.xRot += flap * 0.7F;
                details[1].yRot = Mth.sin(state.ageInTicks * 0.18F) * 0.18F;
            }
            case WARRIOR -> {
                walk(step, opposite, 0.82F);
                tail.yRot = -step * 0.12F;
                tailTip.yRot = -step * 0.18F;
                leftArm.zRot -= 0.08F;
                rightArm.zRot += 0.08F;
            }
            case CRAWLER, BEETLE -> {
                for (int i = 0; i < details.length; i++) {
                    float cycle = Mth.sin(phase * 1.35F + (i % 3) * 0.85F + (i >= 3 ? Mth.PI : 0));
                    details[i].yRot += cycle * 0.25F * speed;
                }
                leftArm.yRot += step * 0.16F;
                rightArm.yRot -= step * 0.16F;
                body.y += Math.abs(Mth.sin(phase * 1.35F)) * speed * -0.18F;
            }
            case PLANT -> {
                body.zRot = idle * 0.06F;
                head.zRot = Mth.sin(state.ageInTicks * 0.11F + 0.6F) * 0.09F;
                jaw.xRot += 0.12F + (Mth.sin(state.ageInTicks * 0.17F) + 1) * 0.08F;
                leftArm.zRot += idle * 0.12F;
                rightArm.zRot -= idle * 0.12F;
            }
            case BOSS -> {
                walk(step, opposite, 0.42F);
                body.y += Math.abs(Mth.sin(phase)) * speed * -0.22F;
                tail.yRot = Mth.sin(state.ageInTicks * 0.08F) * 0.16F;
                tailTip.yRot = Mth.sin(state.ageInTicks * 0.08F + 0.5F) * 0.22F;
                jaw.xRot += (Mth.sin(state.ageInTicks * 0.075F) + 1) * 0.035F;
                shell.xRot = idle * 0.012F;
            }
            case VILLAGER -> {
                // Dedicated ToadModel handles the non-hostile shopkeeper.
            }
        }
    }

    private void walk(float step, float opposite, float armScale) {
        rightLeg.xRot = step;
        leftLeg.xRot = opposite;
        rightArm.xRot = -step * armScale;
        leftArm.xRot = -opposite * armScale;
    }
}
